Repository ssu-student-union/homepage-frontend, pull requests merged in 2024-08, with the labels that each got.

#31 feat: PostHead component 추가
  package.json
  src/components/PostHead/index.tsx
  src/components/Spacing/index.tsx
  src/utils/formatYYYYMMDDHHMM.ts
  yarn.lock
Labels: feat, chore

#33 feat: Floating 컴포넌트 개발
  package.json
  src/assets/image/insta.svg
  src/assets/image/kakao.svg
  src/assets/image/youtube.svg
  src/components/Floating/Floating.tsx
  src/components/Floating/const/index.tsx
Labels: feat

#40 feat: postCardBasic, postCardMissing 컴포넌트 제작
  src/assets/image/profileDefault.png
  src/components/PostCard/PostCardBasicMissing.tsx
  src/components/PostCard/const/state.tsx
  src/components/PostCard/const/style.tsx
  src/components/ui/badge.tsx
  src/containers/common/Header/Header.tsx
  src/containers/common/Header/component/AuthButton.tsx
  src/containers/common/Header/component/DropDownMenu.tsx
  src/containers/common/Header/component/HeaderSheet.tsx
  src/containers/common/Header/component/Navigation.tsx
  src/containers/common/Header/const/pathData.tsx
  tsconfig.json
Labels: feat

#32 feat: register page개발
  .gitignore
  package-lock.json
  src/App.tsx
  src/assets/image/kakao_login_large_narrow.svg
  src/components/FilterDropDown/FilterDropDown.tsx
  src/components/Logo/KakaoButton.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/select.tsx
  src/containers/common/Header/Header.tsx
  src/pages/general/containers/GeneralRegisterSection.tsx
  src/pages/general/containers/index.ts
  src/pages/general/page.tsx
  src/pages/intro/page.tsx
  src/pages/kakao/containers/KakaoAuthHandler.tsx
  src/pages/kakao/containers/KakaoLogin.tsx
  src/pages/kakao/containers/KakaoRedirect.tsx
  src/pages/kakao/containers/RegisterButtonSection.tsx
  src/pages/kakao/containers/RegisterInputSection.tsx
  src/pages/kakao/containers/RegisterTextSection.tsx
  src/pages/kakao/containers/apis/GetToken.tsx
  src/pages/kakao/containers/apis/types/types.d.ts
  src/pages/kakao/page.tsx
  src/pages/router.tsx
  tailwind.config.js
  yarn.lock
Labels: feat

#50 fix: switch classname 사용처에서 적용 안됨
  src/components/Switch/index.tsx
  src/pages/router.tsx
Labels: fix

#41 feat: post card notice post text petition view 컴포넌트 개발
  src/assets/image/pencil.svg
  src/assets/image/thumbsUp.svg
  src/components/PostCard/PostCardBasicMissing.tsx
  src/components/PostCard/PostCardNotice.tsx
  src/components/PostCard/PostTextPetitionView.tsx
  src/components/PostCard/const/style.tsx
Labels: feat
