Repository ssu-student-union/homepage-frontend, pull requests merged in 2025-02, with the labels that each got.

#383 refactor: 서비스공지사항 폰트 수정
  src/pages/mypage/service-notice/[id]/container/serviceNoticeDetailEditSection.tsx
  src/pages/mypage/service-notice/component/ServiceNoticePostContent.tsx
  src/pages/mypage/service-notice/page.tsx
  src/pages/notice/noticeEdit/hook/useNoticeEdit.ts
Labels: hotfix

#403 refactor: 헤더, 메인카드, 하단 푸터 S:SURE로 변경
  package.json
  src/assets/image/logo/ssure_white_logo.svg
  src/components/Logo/SsureLogo.tsx
  src/components/Logo/UssumLogo.tsx
  src/components/MainCarousel/index.tsx
  src/components/PostCard/PostCardBasicMissing.tsx
  src/const/studentCouncil.ts
  src/containers/common/Footer/Footer.tsx
  src/containers/common/Header/Header.tsx
  src/pages/petition-notice/[id]/containers/PostPetitionDetailPostSection.tsx
  src/types/svg.d.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: refactor

#404 feat: 자료집 UI 구현 (RE)
  src/apis/getBoardDataPostSearch.ts
  src/apis/getBoardDataPosts.ts
  src/apis/getOnboardingMail.ts
  src/apis/patchBoardDataPosts.ts
  src/apis/postBoardBoardCodeFiles.ts
  src/apis/postBoardDataFiles.ts
  src/apis/postBoardDataSubCategoryPost.ts
  src/components/BoardNew/detail/PostFooter.tsx
  src/components/ui/button.tsx
  src/components/ui/navigation-menu.tsx
  src/containers/common/Header/component/Navigation.tsx
  src/containers/common/Header/const/pathData.tsx
  src/containers/new/Container.tsx
  src/hooks/useIsOverflow.tsx
  src/pages/audit/auditEdit/container/auditEditImageSection.tsx
  src/pages/main/hook/useTodayPost.tsx
Labels: feat

#407 feat: 자료집 API 연동
  src/components/BoardNew/detail/Attachment.tsx
  src/components/BoardNew/detail/PostBody.tsx
  src/components/BoardNew/edit/FileInput.tsx
  src/components/BoardNew/edit/FileInputWithType.tsx
  src/components/BoardNew/edit/FileInputs.tsx
  src/components/BoardNew/edit/FileInputsWithType.tsx
  src/components/File/FileDownButton.tsx
  src/components/FilterDropDown/FilterDropDown.tsx
  src/containers/common/Header/component/DropDownMenu.tsx
  src/containers/common/Header/component/HeaderSheet.tsx
  src/containers/common/Header/component/Navigation.tsx
  src/containers/common/Header/const/pathData.tsx
  src/hooks/new/mutations/useCreatePost.ts
  src/hooks/new/mutations/useUploadFiles.ts
  src/hooks/new/query/useGetComments.ts
  src/hooks/new/query/useSearchDataPosts.ts
  src/hooks/new/query/useSearchPosts.ts
  src/hooks/useContentEditor.ts
  src/pages/data/[id]/const/mockupData.ts
  src/pages/data/[id]/page.tsx
  src/pages/data/components/DataContentItem.tsx
  src/pages/data/const/category.tsx
  src/pages/data/const/data.ts
  src/pages/data/const/mockupData.ts
  src/pages/data/container/SortLayout.tsx
  src/pages/data/container/SortOptions.tsx
  src/pages/data/edit/form.ts
  src/pages/data/edit/hooks/useDataform.ts
  src/pages/data/edit/page.tsx
  src/pages/data/hook/mutation/useCreateDataPost.ts
  src/pages/data/hook/mutation/usePatchDataPost.ts
  src/pages/data/hook/query/useSearchDataPost.ts
  src/pages/data/hook/utils/useDataCategory.ts
  src/pages/data/page.tsx
  src/pages/data/queries.ts
  src/pages/data/schema.ts
  src/pages/general/containers/GeneralRegisterSection.tsx
  src/pages/human-rights/edit/page.tsx
  src/pages/human-rights/schema.ts
  src/pages/main/hook/useTodayPost.tsx
  src/pages/router.tsx
  src/pages/sug-notice/edit/page.tsx
  src/pages/sug-notice/schema.ts
  src/schemas/common.ts
  src/schemas/post.ts
  src/types/apis/get/index.tsx
Labels: feat

#411 refactor: FileInput 내 FilterDropDown 컴포넌트 위치 변경
  src/components/BoardNew/edit/FileInput.tsx
Labels: refactor

#406 refactor: 서비스공지사항 편집 긴급 체크박스
  src/hooks/api/get/useGetBoardPosts.ts
  src/pages/mypage/service-notice/[id]/container/serviceNoticeDetailEditSection.tsx
  src/pages/mypage/service-notice/service-noticePatch/page.tsx
  src/pages/notice/noticeDetail/container/noticeDetailEditSection.tsx
  src/pages/notice/noticeEdit/container/noticeEditTitleSection.tsx
  src/pages/notice/noticeEdit/hook/useImageManager.ts
  src/pages/notice/noticeEdit/hook/useNoticeEdit.ts
  src/pages/notice/noticePatch/hook/useNoticePatch.ts
  src/pages/notice/noticePatch/page.tsx
  src/types/apis/get/index.tsx
Labels: hotfix

#420 refactor: 온보딩 UI 개선
  src/components/Buttons/KakaoButton.tsx
  src/components/Floating/ChannelTalkFloating.tsx
  src/components/Logo/KakaoButton.tsx
  src/containers/common/Header/Header.tsx
  src/pages/data/edit/page.tsx
  src/pages/general/containers/CertifyApplySection.tsx
  src/pages/general/containers/GeneralRegisterSection.tsx
  src/pages/general/containers/TOSSection.tsx
  src/pages/general/containers/ZodCheck.ts
  src/pages/general/containers/index.ts
  src/pages/general/page.tsx
  src/pages/general/types/onboardingZodCheck.ts
  src/pages/kakao/containers/RegisterButtonSection.tsx
  src/pages/kakao/containers/RegisterTextSection.tsx
  src/pages/main/containers/CounselBtn.tsx
  src/translate/locales/en.json
  src/translate/locales/ko.json
Labels: refactor

#423 style: SSURE 로고 dark ver 추가
  src/assets/image/logo/ssure_logo_dark.svg
  src/components/Logo/SsureLogo.tsx
  src/containers/common/Header/Header.tsx
  src/pages/kakao/containers/RegisterButtonSection.tsx
  src/pages/kakao/containers/RegisterTextSection.tsx
Labels: style

#425 fix: 번역 부분 미적용
  src/containers/common/Header/component/HeaderSheet.tsx
  src/containers/common/Header/component/Navigation.tsx
  src/pages/main/containers/CampusMapSection.tsx
  src/pages/main/containers/MainScheduleSection.tsx
  src/pages/main/containers/NoticeSection.tsx
  src/pages/main/containers/QnaSection.tsx
  src/translate/locales/en.json
  src/translate/locales/ko.json
Labels: fix

#431 fix: passu 리다이랙트 대응
  src/pages/general/containers/GeneralRegisterSection.tsx
Labels: fix
